# Generated by Django 5.0.3 on 2024-06-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bagis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baslik', models.CharField(blank=True, max_length=200, null=True)),
                ('Aciklama', models.TextField(blank=True, null=True)),
                ('Resim', models.ImageField(blank=True, null=True, upload_to='upload/donations')),
                ('Fiyat', models.IntegerField()),
            ],
        ),
    ]
