# Generated by Django 5.0.3 on 2024-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insankaynaklari',
            name='Biyografi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yonetimkurulu',
            name='Biyografi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
